config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :directions
  resources :ingredients
  resources :recipes

  root "recipes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :recipes
 has_many :users, through: :recipes
end

app/models/direction.rb
class Direction < ApplicationRecord

  belongs_to :recipe, optional: true

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe, optional: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def category_title=(title)
     self.category = Category.find_or_create_by(title: title)
   end

   def category_title
      self.category ? self.category.title : nil
end

    belongs_to :category, optional: true
    belongs_to :user
    has_many :ingredients, dependent: :destroy
    has_many :directions, dependent: :destroy
    accepts_nested_attributes_for :ingredients,
                                  allow_destroy: true,
                                  reject_if: proc { |attributes| attributes['name'].blank? }


    accepts_nested_attributes_for :directions,
                                  allow_destroy: true,
                                  reject_if: proc { |attributes| attributes['step'].blank? }
    # accepts_nested_attributes_for :categories,
    #                               allow_destroy: true,
    #                               reject_if: proc { |attributes| attributes['title'].blank? }


    validates :title, :description, :image, presence: true

    has_attached_file :image, styles: { medium: "400x400#"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


  end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :categories, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipe = Recipe.all.order("created_at DESC")
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
    @categories = Category.all
    # @recipe = @category.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "Yay! You have successfully created a new recipe"
    else
      @categories = Category.all

      render 'new'
    end
  end


  def edit
    @categories = Category.all

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      @categories = Category.all

      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    @categories = Category.all
    redirect_to root_path, notice: "Recipe has been deleted!"
  end

  private
  #attributes we want to save to our model
  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy], categories_attributes: [:id, :title, :_destroy])
  end

  #create private method for finding the recipe by id
  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Recipe Rails Project
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Recipe", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Recipe", new_recipe_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete 

      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path

  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert"

    = yield

app/views/recipes/_category_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :title, input_html: { class: 'form-input form-control'} %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
</div>
</div>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: 'form-input form-control'} %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
</div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <div id="errors">
      <p>
        <%= @recipe.errors.count %>
      </p>
      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">
      <%= f.input :title, input_html: { class: 'form-control'} %>
      <%= f.input :description, input_html: { class: 'form-control'} %>
      <%= f.input :image, input_html: { class: 'form-control'} %>
      <%= f.input :ingredients, input_html: { class: 'form-control'} %>
      <%= f.input :directions, input_html: { class: 'form-control'} %>

  </div>
      <%= f.collection_select :category_id, Category.all, :id, :title %>
      <% end %>
      <div class="form-actions">
  <%= f.button :submit, class: "btn btn-primary" %>
    </div>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control'} %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default"  %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render "form" %>

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag recipe.image.url(:medium) %>
            <% end %>
          </div>
          <h2>
            <%= link_to recipe.title, recipe %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>Create New  Recipe</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/show.html.erb
<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <h1>
          <%= @recipe.title %>
        </h1>
        <p class="description">
          <%= @recipe.description %>
        </p>
        <p> Submitted By:
          <%= @recipe.user.email %>
          </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% if user_signed_in? %>
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
      <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-default" %>
    </div>
  </div>
  <% end %>